test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.1319c98657f9b743cd345185aafc51c7a7da342f.name = "Upgrade from 2.0~ynh2"
